### ISSUE TITLE
Bop prevents iTunes COM to dispose

### ISSUE THREAD

**Issue by PZeide** [GoldenCrystal/Bop#1]
When Bop is running, iTunes can't be closed unless you wait ~10 sec to force it to close. iTunes is waiting for every COM communications to dispose but Bop isn't disposing it (at the OnAboutToPromptUserToQuit event).

**Comment by hexawyz** [comment]
I've pushed a change which should fix this problem.
I'll try and see if I can get the service to restart itself when iTunes is restarted (I may have an idea) before publishing a new release.
Thanks for pushing me to look deeper into this, anyway 🙂

**Comment by hexawyz** [comment]
I have published a new release which handles things more gracefully, feel free to check it: https://github.com/GoldenCrystal/Bop/releases/tag/v1.1.0
